routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\AggregationController;
use App\Models\Aggregation;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome', [
        'aggregation' => Aggregation::all(),
        'aggregations_chron' => Aggregation::all()->sortByDesc('created_at')
    ]);
});

Route::resource('aggregations', AggregationController::class);

Route::post('/sets/{id}/upload-documents',
    [AggregationController::class, 'uploadDocuments'])->name('aggregations.uploadDocuments');
Route::get('/quick-reate',
    [AggregationController::class, 'quickCreate'])->name('aggregations.quickCreate');
Route::post('/quick-store',
    [AggregationController::class, 'quickStore'])->name('aggregations.quickStore');

app/Http/Controllers/AggregationController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Collection;
use App\Models\Document;
use App\Models\Aggregation;

class AggregationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('aggregations/create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        date_default_timezone_set('Europe/Berlin');

        $aggregation = Aggregation::create([
            'label' => date('d.m.Y H:i'),
            'signatures' => $request->signatures,
            'origin' => $request->origin,
            'description' => $request->description,
        ]);

        $aggregation->save();

        $this->attach_images($request, $aggregation);

        return redirect('/');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('aggregations/update', [
            'aggregation' => Aggregation::find($id)
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $aggregation = Aggregation::find($id);

        $aggregation->signatures = $request->signatures;
        $aggregation->origin = $request->origin;
        $aggregation->description = $request->description;

        $aggregation->save();

        $this->attach_images($request, $aggregation);

        return redirect('/');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Aggregation::destroy($id);

        return redirect('/');
    }

    protected function attach_images($request, $aggregation) {

        /**
         * 1. go through all form fields and check if a key contains 'image_'
         *    we take the tempid/link to the connected form fields from that
         * 2. check if we already have a document id
         *      - if no, create a new document
         *      - if yes, replace the old one, if a new file is provided
         * 3. last but not least, remove documents that were deleted
         */

        $ids = [];

        foreach($request->all() as $key => $input) {
            if(strpos($key, 'image_') !== false){

                // 1. get image tempid
                $image_tempid = $request->input('image_'.$input);

                // 2. check if the document already exists
                $image_id = $request->input('id_'.$image_tempid);

                if($request->file('document_'.$image_tempid)){
                    $file = $request->file('document_'.$image_tempid);
                    $label = implode('.', explode('.', $file->getClientOriginalName(), -1));
                    $original_file_name = $file->getClientOriginalName();
                    $file_name = time().'_'.$this->gen_uuid().'_'.$original_file_name;
                    $base_path = 'restoration';

                    $file->storeAs(
                        'public/'.$base_path, $file_name
                    );

                    if($image_id != '') {
                        $document = Document::find($image_id);
                    } else {
                        $document = $aggregation->documents()->create();
                    }

                    $document->label = $label;
                    $document->comment = $request->input('comment_'.$image_tempid);
                    $document->file_name = $file_name;
                    $document->original_file_name = $original_file_name;
                    $document->base_path = $base_path;

                    $document->save();

                    // add image id to worked on ids to check
                    $ids[] = $document->id;
                }

                // in case we just need to change the comment of an existing image
                if($image_id != '') {
                    $document = Document::find($image_id);
                    $document->comment = $request->input('comment_'.$image_tempid);
                    $document->save();
                }
                
                // add to worked on ids if image exists but wasn't exchanged
                if(!$request->file('document_'.$image_tempid) && $image_id != '') {
                    $ids[] = $image_id;
                }
            }
        }

        // 3. just sync the worked on images, forgetting the rest
        $aggregation->documents()->sync($ids);
    }

    protected function gen_uuid($l=6){
        return substr(str_shuffle("0123456789abcdefghijklmnopqrstuvwxyz"), 0, $l);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/aggregations/complex/create-complex.blade.php
@extends('base')

@section('content')
<div class="absolute top-4 right-4">
    <x-links.default href="/" label="Home"/>
</div>
<div class="md:flex gap-10">
    <div class="md:w-1/3">
        <h2 class="text-xl font-bold mb-8">1. Edit list of signatures</h2>
        <div>
            @include('sets.set-signatures')
        </div>
        <form action="{{ route('sets.store') }}" method="POST">
        
            @csrf
            
            @include('sets.set-meta')
            
            <div class="mt-10">
                <button type="submit" class="py-1 px-4 bg-black text-white rounded-full">Save Set</button>
            </div>
        </form>

    </div>
</div>

<script>

    function auto_grow(element) {
        element.style.height = "5px";
        element.style.height = (element.scrollHeight)+"px";
    }

</script>

@endsection

resources/views/aggregations/complex/set-meta.blade.php
<div class="mt-10">
    <div class="flex mb-2 items-center gap-2 text-xs">
        <h3>Signatures</h3>
        <a href="javascript:;" id="toggle-view" class="bg-black text-white p-1 rounded-full">
            <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 10h16M4 14h16M4 18h16"></path></svg>
        </a>
        <a href="javascript:;" id="sort-signatures" class="bg-black text-white p-1 rounded-full">
            <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 4h13M3 8h9m-9 4h9m5-4v12m0 0l-4-4m4 4l4-4"></path></svg>
        </a>
    </div>
    <textarea name="signatures" id="signatures" class="w-full h-14 p-4 border border-gray-100 bg-white shadow-xl overflow-hidden" oninput="auto_grow(this)">{{ $set->signatures ?? '' }}</textarea>
</div>

<h2 class="text-xl font-bold mb-8 mt-20">2. Add set information</h2>

<div class="mt-10">
    <h3 class="mb-2 text-xs">Label for set</h3>
    <input type="text" name="label" class="border border-gray-300 p-1 w-full" value="{{ $set->label ?? '' }}">
</div>
<div class="mt-10">
    <h3 class="mb-2 text-xs">Description of set</h3>
    <textarea name="description" id="description" class="w-full h-14 p-4 border border-gray-100 bg-white shadow-xl overflow-hidden" oninput="auto_grow(this)">{{ $set->description ?? '' }}</textarea>
</div>

<script>
    document.addEventListener('DOMContentLoaded', () => {
        auto_grow(document.querySelector('#signatures'));

        let signatures = document.querySelector('#signatures');

        document.querySelector('#toggle-view').addEventListener('click', () => {
            if(signatures.value.includes(',')) {
                signatures.value = signatures.value.split(',').join('\n');
            } else {
                signatures.value = signatures.value.split('\n').join(',');
            }
            auto_grow(signatures);
        });
        document.querySelector('#sort-signatures').addEventListener('click', () => {
            let signatures_array = [];

            if(signatures.value.includes(',')) {
                signatures_array = signatures.value.split(',');
                signatures_array.sort();
                signatures.value = signatures_array.join(',');
            } else {
                signatures_array = signatures.value.split('\n');
                signatures_array.sort();
                signatures.value = signatures_array.join('\n');
            }
        });
    })
</script>

resources/views/aggregations/complex/set-signatures.blade.php
<h3 class="mb-2 text-xs">Add range of signatures</h3>
<div class="flex gap-2">
    <span class="py-1">SGV_</span>
    <input type="text" id="collection" placeholder="10P" class="border border-gray-300 p-1 w-10">
    <span class="py-1">_</span>
    <input type="number" placeholder="1" min="0" max="99999" id="range_start" class="border border-gray-300 p-1 w-20">
    <span class="py-1">bis</span>
    <input type="number" placeholder="10" min="0" max="99999" id="range_end" class="border border-gray-300 p-1 w-20">
    <button id="add_range" class="py-1 px-4 bg-black text-white text-xs rounded-full">Add</button>
</div>

<script>

    document.addEventListener('DOMContentLoaded', () => {
        let add_range = document.querySelector('#add_range'),
            collection = document.querySelector('#collection'),
            range_start = document.querySelector('#range_start'),
            range_end = document.querySelector('#range_end'),
            signatures = document.querySelector('#signatures');

        add_range.addEventListener('click', () => {
            if(collection.value != '' && range_start.value != '' && range_end.value != '') {
                if(signatures.value != '' && signatures.value.substring(signatures.value.length-1) != ',') {
                    signatures.value += ',';
                }
                for(let i = range_start.value; i <= range_end.value; i++) {
                    signatures.value += 'SGV_'+collection.value+'_'+pad(i, 5)+',';
                }
                signatures.value = signatures.value.replace(/,\s*$/, "");
                auto_grow(signatures);
            } else {
                alert('Fill out all necessary fields.');
            }
        })
    })

    function pad(num, size) {
        num = num.toString();
        while (num.length < size) num = "0" + num;
        return num;
    }

</script>

resources/views/aggregations/complex/update-complex.blade.php
@extends('base')

@section('content')
<div class="absolute top-4 right-4">
    <x-links.default href="/" label="Home"/>
    <form action="{{ route('sets.destroy', [$set]) }}" method="post" class="inline-block">
        @csrf
        @method('delete')

        <x-buttons.delete/>
    </form>
</div>
<div class="md:flex gap-10">
    <div class="md:w-1/3">
        <h2 class="text-xl font-bold mb-8">1. Edit list of signatures</h2>
        <div>
            @include('sets.set-signatures')
        </div>
        <form action="{{ route('sets.update', [$set]) }}" method="POST">
        
            @csrf
            @method('patch')
            
            @include('sets.set-meta')
            
            <div class="mt-10">
                <button type="submit" class="py-1 px-4 bg-black text-white rounded-full">Save Set</button>
            </div>
        </form>

    </div>

    <div class="md:w-2/3 md:border-l border-gray-300 md:pl-8 mt-20 md:mt-0">
        <h2 class="text-xl font-bold mb-8">3. Add documents</h2>
        <div class="mb-10">
            <h2 class="text-xs mb-2">Documents</h2>
            <div>
                <ul class="grid grid-cols-3 gap-2">
                @foreach ($set->documents as $document)
                    <li class="mb-2">
                        @if(preg_match('(\.jpg|\.jpeg|\.png)', $document->file_name) === 1)
                            <a href="/{{ 'storage/' . $document->base_path . '/' . $document->file_name }}">
                                <img src="/{{ 'storage/' . $document->base_path . '/' . $document->file_name }}" alt="{{ $document->file_name }}">
                            </a>
                        @else
                            <x-links.default :label="$document->label" href="/{{ 'storage/' . $document->base_path . '/' . $document->file_name }}"/>
                        @endif
                            <p class="text-xs p-1 pl-3">{{ $document->comment }}</p>
                    </li>
                @endforeach
                </ul>
            </div>
            <hr class="my-8">
            <form class="inline-block" x-data x-ref="documentsupload" method="POST" enctype="multipart/form-data" action="{{ route('sets.uploadDocuments', [$set]) }}">
                @csrf
                <input type="file" name="documents[]" class="mb-2" required multiple>
                <textarea name="comment" id="comment" class="border border-gray-300 p-1 w-full mb-2" placeholder="Comment"></textarea>
                <x-buttons.default type="submit" label="Upload documents"/>
            </form>
        </div>
    </div>
</div>

<script>

    function auto_grow(element) {
        element.style.height = "5px";
        element.style.height = (element.scrollHeight)+"px";
    }

</script>

@endsection

resources/views/aggregations/create.blade.php
@extends('base')

@section('content')
    <div class="overflow-x-hidden">
        <form action="{{ route('aggregations.store') }}" method="POST" enctype="multipart/form-data">
            @csrf

            @include('aggregations.partials.update-meta')

            <div class="mb-8">
                <h3 class="mb-2 font-bold">Fotos</h3>
                <div id="image_wrapper"></div>
            </div>

            @include('aggregations.partials.update-actions')
        </form>
    </div>

    <template id="image_template">
        @include('aggregations.partials.update-image')
    </template>

    @include('aggregations.partials.update-scripts')

@endsection

resources/views/aggregations/partials/update-actions.blade.php
<div class="mb-8 text-right">
    <button type="button" class="py-1 px-3 rounded-full border border-black hover:bg-black hover:text-white transition"
        onclick="add_image()">Neues Foto hinzufügen</button>
</div>

<div class="mb-8 text-right">
    <a href="/" class="text-xs underline mr-2">Abbrechen</a>
    <button type="submit" class="inline-block py-1 px-3 rounded-full border border-green-500 bg-green-500 text-white hover:bg-white hover:text-green-500 transition">Notiz speichern</button>
</div>

resources/views/aggregations/partials/update-image.blade.php
<div class="image mb-4 p-2 bg-gray-100 relative">
    <input type="hidden" name="image_{{ $datenow ?? 'IMAGEID' }}" value="{{ $datenow ?? 'IMAGEID' }}">
    <input type="hidden" name="id_{{ $datenow ?? 'IMAGEID' }}" value="{{ $img->id ?? '' }}">
    <input type="file" accept="image/*" name="document_{{ $datenow ?? 'IMAGEID' }}" class="mb-2" onchange="show_preview(event)">
    <div class="mb-2">
        @if(isset($img) && $img->file_name)
            <img class="preview w-full max-w-xl" src="/{{ 'storage/' . $img->base_path . '/' . $img->file_name }}" alt="{{ $img->file_name }}">
        @else
            <img class="preview w-full max-w-xl">
        @endif
    </div>
    <textarea name="comment_{{ $datenow ?? 'IMAGEID' }}" class="border border-gray-300 p-1 w-full" oninput="auto_grow(this)" placeholder="Kommentar zu Foto hinzufügen">{{ $img->comment ?? '' }}</textarea>
    <div class="absolute top-2 right-2 text-right">
        <button type="button" class="py-1 px-3 bg-red-500 text-white rounded-full text-xs"
onclick="remove_image(event)">x</button>
    </div>
</div>

resources/views/aggregations/partials/update-meta.blade.php
<div class="mb-4">
    <h3 class="mb-2 font-bold">Signaturen *</h3>
    <input type="text" name="signatures" class="border border-gray-300 p-2 w-full" value="{{ $aggregation->signatures ?? '' }}" required>
</div>
<div class="mb-4">
    <h3 class="mb-2 font-bold">Erfasst durch *</h3>
    <input type="text" name="origin" class="border border-gray-300 p-2 w-full" value="{{ $aggregation->origin ?? '' }}" required>
</div>

<div class="mb-8">
    <h3 class="mb-2 text-xs">Allgmeiner Kommentar (optional)</h3>
    <textarea type="text" name="description" class="border border-gray-300 p-2 w-full" oninput="auto_grow(this)">{{ $aggregation->description ?? '' }}</textarea>
</div>

resources/views/aggregations/partials/update-scripts.blade.php
<script>

    document.addEventListener('DOMContentLoaded', () => {
        document.querySelectorAll('textarea').forEach(el => {
            el.style.height = "5px";
            el.style.height = (el.scrollHeight)+"px";
        })
    
        let origin = document.querySelector('[name="origin"]');

        if(origin.value == '' && localStorage.getItem('origin') != '') {
            origin.value = localStorage.getItem('origin');
        }

        origin.addEventListener('change', () => {
            localStorage.setItem('origin', origin.value);
        })
    })

    let template = document.querySelector('#image_template'),
        image_wrapper = document.querySelector('#image_wrapper');

    function auto_grow(element) {
        element.style.height = "5px";
        element.style.height = (element.scrollHeight)+"px";
    }

    function show_preview(evt){
        if (evt.target.files.length > 0) {
            var preview = URL.createObjectURL(evt.target.files[0]);
            evt.target.parentNode.querySelector('img.preview').src = preview;
        }
    }

    function add_image() {
        let img = document.createElement('div');
        
        img.innerHTML = template.innerHTML.replace(/IMAGEID/g, Date.now());
        image_wrapper.appendChild(img);
    }

    function remove_image(evt){
        let target = evt.target.closest('.image');
        target.parentNode.removeChild(target);
    }

</script>

resources/views/aggregations/update.blade.php
@extends('base')

@section('content')
    <div class="overflow-x-hidden">
        <form action="{{ route('aggregations.update', $aggregation) }}" method="POST" enctype="multipart/form-data">
            @csrf
            @method('put')

            @include('aggregations.partials.update-meta')

            <div class="mb-8">
                <h3 class="mb-2 font-bold">Fotos</h3>
                <div id="image_wrapper">
                    @foreach ($aggregation->documents as $image)
                        @include('aggregations.partials.update-image', [
                            'datenow' => time() . '_' . $loop->index,
                            'img' => $image
                        ])
                    @endforeach
                </div>
            </div>

            @include('aggregations.partials.update-actions')
        </form>
    </div>

    <form action="{{ route('aggregations.destroy', [$aggregation]) }}" method="post">
        @csrf
        @method('delete')
        <x-buttons.delete/>
    </form>

    <template id="image_template">
        @include('aggregations.partials.update-image')
    </template>

    @include('aggregations.partials.update-scripts')

@endsection

resources/views/base.blade.php
<!DOCTYPE html>
<html lang="de">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PIA Restoration Notes</title>

    <link href="/styles.css" rel="stylesheet">
    
    @yield('styles')

</head>
<body class="overflow-x-hidden p-4">

    <h1 class="text-3xl font-bold"><a href="/">PIA Restoration</a></h1>
    <p class="mb-4 w-full text-xs md:w-1/2">Mit diesem Werkzeug lassen sich Notizen, Fotos und andere Dokumente an Signaturen hängen. Ein zukünftigen Werkzeug wird diese Signaturen auslesen und die Dokumente mit den digitalisierten Objekten verknüpfen.</p>

    @yield('content')
    
    <a href="/" class="fixed top-2 right-2">
        <img class="w-10" src="{{ asset('pia-rat.svg') }}" alt="PIA Logo Rat">
    </a>

    <!--<script defer src="https://unpkg.com/@alpinejs/persist@3.x.x/dist/cdn.min.js"></script>-->
    <!--<script defer src="https://unpkg.com/@alpinejs/intersect@3.x.x/dist/cdn.min.js"></script>-->
    <!-- <script defer src="https://unpkg.com/alpinejs@3.x.x/dist/cdn.min.js"></script> -->

    @yield('scripts')

</body>
</html>

resources/views/collections/view.blade.php
<div class="flex gap-2">
    <div class="w-1/2">
        <div class="mb-10">
            <h2 class="text-xs mb-2">Documents</h2>
            <div>
                <ul>
                @foreach ($collection->documents as $document)
                    <li class="mb-2"><x-links.default :label="$document->label" href="/{{ 'storage/' . $document->base_path . '/' . $document->file_name }}"/></li>
                @endforeach
                </ul>
            </div>
            <form class="inline-block" x-data x-ref="documentsupload" method="POST" enctype="multipart/form-data" action="{{ route('collections.uploadDocuments', [$collection]) }}">
                @csrf
                <input x-ref="documents" @change="$refs.documentsupload.submit()" class="hidden" type="file" name="documents[]" required multiple>
                <x-buttons.default @click="$refs.documents.click()" label="Upload documents"/>
            </form>
        </div>
        <div class="mb-10">
            <h2 class="text-xs mb-2">Notes</h2>
            <div>
                <ul>
                @foreach ($collection->docs as $doc)
                    <li class="mb-2"><x-links.default :label="$doc->label" href="{{ env('DOCS_URL') }}/{{ $doc->id }}/edit"/></li>
                @endforeach
                </ul>

                <form action="{{ env('DOCS_URL') }}/create" method="get" class="inline-block">
                    @csrf
                    <input type="hidden" name="collections" value="{{ $collection->id }}">
                    <input type="hidden" name="label" value="{{ $collection->label }}">
                    
                    <x-buttons.default label="New Note" type="submit"/>
                </form>
            </div>
        </div>
        <div class="">
            <h2 class="text-xs mb-2">Maps</h2>
            <div>
                <ul>
                @foreach ($collection->maps as $map)
                    <li class="mb-2"><x-links.default :label="$map->label" href="{{ env('MAPS_URL') }}/{{ $map->id }}"/></li>
                @endforeach
                </ul>

                <form action="{{ env('MAPS_URL') }}/create" method="get" class="inline-block">
                    @csrf
                    <input type="hidden" name="collections" value="{{ $collection->id }}">
                    <input type="hidden" name="label" value="{{ $collection->label }}">
                    
                    <x-buttons.default label="New Map" type="submit"/>
                </form>
            </div>
        </div>
    </div>
    <div class="w-1/2">
        <h2 class="text-xs mb-2">Images</h2>
        <form x-ref="imageupload" method="POST" enctype="multipart/form-data" action="{{ route('collections.uploadImage', [$collection]) }}" x-data>
            @csrf
            <input x-ref="images" @change="$refs.imageupload.submit()" class="hidden" type="file" name="images[]" accept="image/*" required multiple>
            <x-buttons.default @click="$refs.images.click()" label="Upload images"/>
        </form>

        <div class="grid gap-2 grid-flow-row grid-cols-1 md:grid-cols-2 lg:grid-cols-2 xl:grid-cols-3 mt-4">
            @foreach ($collection->images as $image)
                <a href="{{ env('PIA_URL') }}images/{{ $image->id }}" class="print-image">
                    <img class="inline-block mr-2 w-full" src="https://pia-iiif.dhlab.unibas.ch/{{$image->base_path != '' ? $image->base_path.'/' : ''}}{{$image->signature}}.jp2/full/360,/0/default.jpg" alt="{{$image->title}}" title="{{$image->title}}">
                </a>
            @endforeach
        </div>
    </div>
</div>